volumes:
  db-data:
    driver: local

networks:
  db-ws-lan:
    driver: bridge

secrets:
  db-password:
    file: .dbpassword
  init-password:
    file: .initpassword
  secret-key:
    file: .secretkey

services:
  sql-server:
    image: mysql:8
    container_name: sql-server
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - db-ws-lan
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always
    ports:
      - 3370:3306
